// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO69vLt8K2FdYjkmHyCxloDGQqFHhRGCY',
    appId: '1:3722977204:web:b2c63b572e571deffd1ce1',
    messagingSenderId: '3722977204',
    projectId: 'samplefirebase-830ba',
    authDomain: 'samplefirebase-830ba.firebaseapp.com',
    storageBucket: 'samplefirebase-830ba.appspot.com',
    measurementId: 'G-M6M5ERW3QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldaNNBmhMzpIYPwiuIahe0lN3kUUWqFA',
    appId: '1:3722977204:android:2a7d7f9c1a13b963fd1ce1',
    messagingSenderId: '3722977204',
    projectId: 'samplefirebase-830ba',
    storageBucket: 'samplefirebase-830ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9i9jVFCUxJvF6RzNkxFv1EE4FwQtdN5Y',
    appId: '1:3722977204:ios:505c2dffa4435e83fd1ce1',
    messagingSenderId: '3722977204',
    projectId: 'samplefirebase-830ba',
    storageBucket: 'samplefirebase-830ba.appspot.com',
    iosBundleId: 'com.example.machineTest1',
  );
}
